name: הבדיקות שלי

on: [push] # הרובוט יופעל בכל פעם שתעלה קוד

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: הכנת סביבת עבודה
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: התקנת כלים
      run: npm install

    - name: הרצת הבדיקה
      run: npm test
      