name: הבדיקות שלי

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      - name: Run tests
        run: npm test